trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_Test
  jobs:
  - job: Maven_Package
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'microservices/account-service/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
      displayName: 'Build'
- stage: Deploy_Stage
  dependsOn: Build_Test
  jobs:
    - deployment: Deployment_Staging
      environment:
        name: demo 
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureSpringCloud@0
              inputs:
                azureSubscription: $(subscription)
                Action: 'Deploy'
                AzureSpringCloud: $(serviceName)
                AppName: 'account-service'
                DeploymentName: envv2