trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_Test
  jobs:
  - job: Maven_Package
    steps:
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'pminkows'
        mavenServiceConnections: 'pminkows'
      displayName: 'Maven Authenticate'
    - task: Maven@3
      inputs:
        mavenPomFile: 'microservices/account-service/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'deploy'
        mavenAuthenticateFeed: true
      displayName: 'Build'
- stage: Deploy_Stage
  dependsOn: Build_Test
  condition: succeeded()
  jobs:
    - deployment: Deployment_Staging
      environment:
        name: staging
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPackage@1
              inputs:
                packageType: 'maven'
                feed: 'pminkows'
                view: 'Local'
                definition: '59ff6956-2828-408d-955d-dfe0b62838b9'
                version: '1.0'
                downloadPath: '$(System.ArtifactsDirectory)'
            - script: 'ls -la $(System.ArtifactsDirectory)' 
            - task: AzureSpringCloud@0
              inputs:
                azureSubscription: $(subscription)
                Action: 'Deploy'
                AzureSpringCloud: $(serviceName)
                AppName: 'account-service'
                DeploymentName: dep1
                Package: '$(System.ArtifactsDirectory)/account-service.jar'